"""Slice 39G MeaningStructureManifest candidate-integration exports."""

from .adapter import (
    DEFAULT_MANIFEST_INTEGRATION_PROFILE,
    integrate_candidate_meanings_into_manifest,
)
from .authority import (
    SLICE39G_ADAPTER_DECISION,
    SLICE39G_ADAPTER_DECISION_REASONS,
    SLICE39G_COMPANION_VERSION,
    SLICE39G_PERMANENT_BOUNDARIES,
    SLICE39G_PROFILE_VERSION,
    SLICE39G_PROHIBITED_AUTHORITY,
    SLICE39G_REQUIRED_EMPTY_MANIFEST_SECTIONS,
    SLICE39G_REQUIRED_PATH,
    SLICE39G_SCHEMA_VERSION,
    SLICE39G_SPEC_ID,
    SLICE39G_SPEC_VERSION,
)
from .canonical import canonical_json_bytes, deterministic_digest, stable_identifier
from .identity import (
    expected_alternative_relationship_id,
    expected_companion_id,
    expected_limitation_reference_id,
    expected_profile_id,
    expected_provenance_reference_id,
    expected_result_digest,
    expected_result_id,
    expected_trace_reference_id,
)
from .schema import (
    CandidateAlternativeRelationshipV1,
    CandidateConstructionTraceReferenceV1,
    CandidateLimitationReferenceV1,
    CandidateMeaningManifestCompanionV1,
    CandidateProvenanceReferenceV1,
    ManifestCandidateIntegrationProfile,
    ManifestCandidateIntegrationResult,
    ManifestCandidateIntegrationStatus,
    ManifestCandidateIntegrationValidationCode,
    ManifestCandidateIntegrationValidationError,
    ManifestCandidateIntegrationValidationIssue,
    ManifestCandidateIntegrationValidationReport,
)
from .validation import (
    assert_valid_integration_result,
    validate_integration_result,
    validate_profile,
)

__all__ = (
    "DEFAULT_MANIFEST_INTEGRATION_PROFILE",
    "SLICE39G_ADAPTER_DECISION",
    "SLICE39G_ADAPTER_DECISION_REASONS",
    "SLICE39G_COMPANION_VERSION",
    "SLICE39G_PERMANENT_BOUNDARIES",
    "SLICE39G_PROFILE_VERSION",
    "SLICE39G_PROHIBITED_AUTHORITY",
    "SLICE39G_REQUIRED_EMPTY_MANIFEST_SECTIONS",
    "SLICE39G_REQUIRED_PATH",
    "SLICE39G_SCHEMA_VERSION",
    "SLICE39G_SPEC_ID",
    "SLICE39G_SPEC_VERSION",
    "CandidateAlternativeRelationshipV1",
    "CandidateConstructionTraceReferenceV1",
    "CandidateLimitationReferenceV1",
    "CandidateMeaningManifestCompanionV1",
    "CandidateProvenanceReferenceV1",
    "ManifestCandidateIntegrationProfile",
    "ManifestCandidateIntegrationResult",
    "ManifestCandidateIntegrationStatus",
    "ManifestCandidateIntegrationValidationCode",
    "ManifestCandidateIntegrationValidationError",
    "ManifestCandidateIntegrationValidationIssue",
    "ManifestCandidateIntegrationValidationReport",
    "assert_valid_integration_result",
    "canonical_json_bytes",
    "deterministic_digest",
    "expected_alternative_relationship_id",
    "expected_companion_id",
    "expected_limitation_reference_id",
    "expected_profile_id",
    "expected_provenance_reference_id",
    "expected_result_digest",
    "expected_result_id",
    "expected_trace_reference_id",
    "integrate_candidate_meanings_into_manifest",
    "stable_identifier",
    "validate_integration_result",
    "validate_profile",
)
