"""Slice 36B0 RSOC/FBSC language-operator contract and legacy isolation.

This package is intentionally absent from the bootstrap root exports. Explicit
import creates inert immutable contracts only and grants no operator, phase,
meaning, memory, route, tool, action, or delivery authority.
"""

from .field_contract import (
    build_unprojected_language_field,
    evaluate_operator_application,
)
from .legacy_isolation import (
    build_default_legacy_isolation_catalog,
    isolation_record_for_surface,
)
from .registry import (
    build_default_rsoc_operator_registry,
    operator_contract_for_glyph,
    operator_contract_for_key,
)
from .schema import (
    CONTRACT_SCHEMA_VERSION,
    CONTRACT_SPEC_ID,
    CONTRACT_SPEC_VERSION,
    EXPECTED_RSOC_OPERATOR_COUNT,
    FBSC_AUTHORITY_REF,
    FIELD_SCHEMA_ID,
    LEGACY_ISOLATION_SCHEMA_ID,
    OPERATOR_SCHEMA_ID,
    REGISTRY_SCHEMA_ID,
    RMC_LANGUAGE_LAW_AUTHORITY_REF,
    RSOC_AUTHORITY_REF,
    SLICE36A_AUTHORITY_REF,
    FieldContainmentStatus,
    FieldEnvelopeBuildResult,
    FieldEnvelopeBuildStatus,
    FieldPhaseStatus,
    FieldProjectionStatus,
    FieldSupportStatus,
    LegacyIsolationCatalog,
    LegacyIsolationRecord,
    LegacySurfaceCategory,
    LegacySurfaceDisposition,
    LineageIdentityHandling,
    OperatorApplicationDecision,
    OperatorApplicationStatus,
    OperatorArity,
    OperatorRuntimeStatus,
    ResonantLanguageFieldEnvelope,
    RsocLanguageOperatorRegistry,
    RsocOperatorContract,
)
from .validation import (
    validate_field_envelope_build_result,
    validate_legacy_isolation_catalog,
    validate_legacy_isolation_record,
    validate_operator_application_decision,
    validate_resonant_language_field,
    validate_rsoc_language_operator_registry,
    validate_rsoc_operator_contract,
)

__all__ = (
    "CONTRACT_SCHEMA_VERSION",
    "CONTRACT_SPEC_ID",
    "CONTRACT_SPEC_VERSION",
    "EXPECTED_RSOC_OPERATOR_COUNT",
    "FBSC_AUTHORITY_REF",
    "FIELD_SCHEMA_ID",
    "LEGACY_ISOLATION_SCHEMA_ID",
    "OPERATOR_SCHEMA_ID",
    "REGISTRY_SCHEMA_ID",
    "RMC_LANGUAGE_LAW_AUTHORITY_REF",
    "RSOC_AUTHORITY_REF",
    "SLICE36A_AUTHORITY_REF",
    "FieldContainmentStatus",
    "FieldEnvelopeBuildResult",
    "FieldEnvelopeBuildStatus",
    "FieldPhaseStatus",
    "FieldProjectionStatus",
    "FieldSupportStatus",
    "LegacyIsolationCatalog",
    "LegacyIsolationRecord",
    "LegacySurfaceCategory",
    "LegacySurfaceDisposition",
    "LineageIdentityHandling",
    "OperatorApplicationDecision",
    "OperatorApplicationStatus",
    "OperatorArity",
    "OperatorRuntimeStatus",
    "ResonantLanguageFieldEnvelope",
    "RsocLanguageOperatorRegistry",
    "RsocOperatorContract",
    "build_default_legacy_isolation_catalog",
    "build_default_rsoc_operator_registry",
    "build_unprojected_language_field",
    "evaluate_operator_application",
    "isolation_record_for_surface",
    "operator_contract_for_glyph",
    "operator_contract_for_key",
    "validate_field_envelope_build_result",
    "validate_legacy_isolation_catalog",
    "validate_legacy_isolation_record",
    "validate_operator_application_decision",
    "validate_resonant_language_field",
    "validate_rsoc_language_operator_registry",
    "validate_rsoc_operator_contract",
)
