"""Slice 33 deterministic read-only trace and receipt assembly.

Importing this subpackage does not run a fixture, load a component, write a
trace, persist a receipt, or connect Forge runtime surfaces.
"""

from .assembler import assemble_trace_receipt
from .flow_catalog import (
    FLOW_S31_DISABLED_DEFAULT,
    FLOW_S31_EXPLICIT_DISABLED,
    FLOW_S31_EXPLICIT_ENABLED,
    FLOW_S32_DISABLED,
    FLOW_S32_ENABLED,
    get_trace_flow,
    is_exact_accepted_trace_flow,
    list_trace_flows,
)
from .schema import (
    ASSEMBLY_COMPLETED_REASON,
    ASSEMBLY_DISABLED_REASON,
    MODE_DISABLED_DEFAULT,
    MODE_EXPLICIT_OFFLINE_TRACE_RECEIPT,
    STATUS_COMPLETED,
    STATUS_HELD_INVALID_STATE,
    STATUS_HELD_RECEIPT_MISMATCH,
    STATUS_HELD_SOURCE_RESULT_MISMATCH,
    STATUS_HELD_TRACE_MISMATCH,
    STATUS_HELD_UNKNOWN_FLOW,
    STATUS_REFUSED_DISABLED,
    TRACE_RECEIPT_SCHEMA_VERSION,
    AcceptedTraceFlowSpec,
    DerivationReceiptRecord,
    DerivationTraceRecord,
    DerivationTraceStep,
    TraceReceiptAssemblyResult,
    TraceReceiptAssemblyState,
    build_trace_receipt_assembly_state,
    validate_derivation_receipt_record,
    validate_derivation_trace_record,
    validate_derivation_trace_step,
    validate_trace_flow_spec,
    validate_trace_receipt_assembly_result,
    validate_trace_receipt_assembly_state,
)

__all__ = (
    "ASSEMBLY_COMPLETED_REASON",
    "ASSEMBLY_DISABLED_REASON",
    "AcceptedTraceFlowSpec",
    "DerivationReceiptRecord",
    "DerivationTraceRecord",
    "DerivationTraceStep",
    "FLOW_S31_DISABLED_DEFAULT",
    "FLOW_S31_EXPLICIT_DISABLED",
    "FLOW_S31_EXPLICIT_ENABLED",
    "FLOW_S32_DISABLED",
    "FLOW_S32_ENABLED",
    "MODE_DISABLED_DEFAULT",
    "MODE_EXPLICIT_OFFLINE_TRACE_RECEIPT",
    "STATUS_COMPLETED",
    "STATUS_HELD_INVALID_STATE",
    "STATUS_HELD_RECEIPT_MISMATCH",
    "STATUS_HELD_SOURCE_RESULT_MISMATCH",
    "STATUS_HELD_TRACE_MISMATCH",
    "STATUS_HELD_UNKNOWN_FLOW",
    "STATUS_REFUSED_DISABLED",
    "TRACE_RECEIPT_SCHEMA_VERSION",
    "TraceReceiptAssemblyResult",
    "TraceReceiptAssemblyState",
    "assemble_trace_receipt",
    "build_trace_receipt_assembly_state",
    "get_trace_flow",
    "is_exact_accepted_trace_flow",
    "list_trace_flows",
    "validate_derivation_receipt_record",
    "validate_derivation_trace_record",
    "validate_derivation_trace_step",
    "validate_trace_flow_spec",
    "validate_trace_receipt_assembly_result",
    "validate_trace_receipt_assembly_state",
)
