"""Public Slice 37F structural-to-concept candidate proposal surface."""

from .identity import with_expected_id
from .profile import build_default_structural_concept_proposal_profile
from .proposal import propose_structural_concept_candidates
from .schema import (
    CONCEPT_PROPOSAL_SCHEMA_ID,
    LEXICAL_OCCURRENCE_SCHEMA_ID,
    PROPOSAL_PROFILE_SCHEMA_ID,
    PROPOSAL_RESULT_SCHEMA_ID,
    REGISTRY_SNAPSHOT_SCHEMA_ID,
    SENSE_PROPOSAL_SCHEMA_ID,
    SLICE37F_ACCEPTED_PARENT_HEAD,
    SLICE37F_ACCEPTED_PARENT_SUBJECT,
    SLICE37F_ACCEPTED_PARENT_TREE,
    SLICE37F_NON_AUTHORITY_BOUNDARIES,
    SLICE37F_SCHEMA_VERSION,
    SLICE37F_SPEC_ID,
    SLICE37F_SPEC_VERSION,
    STRUCTURAL_ANCESTRY_SCHEMA_ID,
    ConceptCandidateProposal,
    ExactLexicalOccurrenceProposal,
    LexicalOccurrenceDisposition,
    ProposalResultStatus,
    RegistrySnapshotIdentity,
    SenseCandidateProposal,
    StructuralCandidateAncestry,
    StructuralConceptCandidateProposalResult,
    StructuralConceptProposalProfile,
)
from .validation import (
    ProposalValidationReport,
    assert_proposal_profile,
    assert_proposal_result,
    validate_concept_candidate,
    validate_lexical_occurrence,
    validate_proposal_profile,
    validate_proposal_result,
    validate_registry_snapshot,
    validate_sense_candidate,
    validate_structural_ancestry,
)

__all__ = (
    "CONCEPT_PROPOSAL_SCHEMA_ID",
    "LEXICAL_OCCURRENCE_SCHEMA_ID",
    "PROPOSAL_PROFILE_SCHEMA_ID",
    "PROPOSAL_RESULT_SCHEMA_ID",
    "REGISTRY_SNAPSHOT_SCHEMA_ID",
    "SENSE_PROPOSAL_SCHEMA_ID",
    "SLICE37F_ACCEPTED_PARENT_HEAD",
    "SLICE37F_ACCEPTED_PARENT_SUBJECT",
    "SLICE37F_ACCEPTED_PARENT_TREE",
    "SLICE37F_NON_AUTHORITY_BOUNDARIES",
    "SLICE37F_SCHEMA_VERSION",
    "SLICE37F_SPEC_ID",
    "SLICE37F_SPEC_VERSION",
    "STRUCTURAL_ANCESTRY_SCHEMA_ID",
    "ConceptCandidateProposal",
    "ExactLexicalOccurrenceProposal",
    "LexicalOccurrenceDisposition",
    "ProposalResultStatus",
    "ProposalValidationReport",
    "RegistrySnapshotIdentity",
    "SenseCandidateProposal",
    "StructuralCandidateAncestry",
    "StructuralConceptCandidateProposalResult",
    "StructuralConceptProposalProfile",
    "assert_proposal_profile",
    "assert_proposal_result",
    "build_default_structural_concept_proposal_profile",
    "propose_structural_concept_candidates",
    "validate_concept_candidate",
    "validate_lexical_occurrence",
    "validate_proposal_profile",
    "validate_proposal_result",
    "validate_registry_snapshot",
    "validate_sense_candidate",
    "validate_structural_ancestry",
    "with_expected_id",
)
