"""Slice 39D candidate-only semantic content assembly.

This package assembles deterministic possible semantic content from exact
Slice 39C predecessor custody. It does not rank or select candidates, assign
participants, emit clarification, evaluate gates, determine truth or evidence,
grant permission, create routes, invoke tools, perform actions, access memory,
render output, or deliver anything.
"""

from .assembly import (
    DEFAULT_CONTENT_PROFILE,
    assemble_candidate_semantic_content,
    make_semantic_relation_candidate_reference,
)
from .authority import (
    SLICE39D_CONTENT_FAMILIES,
    SLICE39D_DEFERRED_SCOPE,
    SLICE39D_PERMANENT_BOUNDARIES,
)
from .canonical import (
    CANONICAL_FIELD_ORDERS,
    CandidateSemanticContentCanonicalizationError,
    canonical_field_order,
    canonical_json_bytes,
    canonical_record_mapping_39d,
    deterministic_digest,
    deterministic_record_digest,
    stable_identifier,
)
from .identity import (
    expected_assembly_digest,
    expected_assembly_id,
    expected_communicative_purpose_id,
    expected_distinction_id,
    expected_payload_id,
    expected_profile_id,
    expected_referent_id,
    expected_requested_act_id,
    expected_result_id,
    expected_semantic_relation_reference_id,
    with_expected_assembly_identity,
    with_expected_id,
)
from .schema import (
    DIGEST_ALGORITHM,
    SLICE39D_ACCEPTED_PARENT_HEAD,
    SLICE39D_ACCEPTED_PARENT_SUBJECT,
    SLICE39D_ACCEPTED_PARENT_TREE,
    SLICE39D_PROFILE_VERSION,
    SLICE39D_SCHEMA_VERSION,
    SLICE39D_SPEC_ID,
    SLICE39D_SPEC_VERSION,
    CandidateCommunicativePurpose,
    CandidateReferentReference,
    CandidateRequestedActDescription,
    CandidateSemanticContentAssembly,
    CandidateSemanticContentAssemblyResult,
    CandidateSemanticContentPayload,
    CandidateSemanticContentProfileIdentity,
    CandidateSemanticContentStatus,
    CandidateSemanticContentValidationCode,
    CandidateSemanticContentValidationError,
    CandidateSemanticContentValidationIssue,
    CandidateSemanticContentValidationReport,
    CandidateSemanticDistinction,
    CandidateSemanticRelationReference,
    CommunicativeForceCandidate,
    ReferentCandidateKind,
    SemanticDistinctionKind,
)
from .validation import (
    assert_valid_assembly,
    assert_valid_assembly_result,
    validate_assembly,
    validate_assembly_result,
    validate_communicative_purpose,
    validate_distinction,
    validate_payload,
    validate_profile,
    validate_referent_reference,
    validate_requested_act,
    validate_semantic_relation_reference,
)

__all__ = (
    "CANONICAL_FIELD_ORDERS",
    "DEFAULT_CONTENT_PROFILE",
    "DIGEST_ALGORITHM",
    "SLICE39D_ACCEPTED_PARENT_HEAD",
    "SLICE39D_ACCEPTED_PARENT_SUBJECT",
    "SLICE39D_ACCEPTED_PARENT_TREE",
    "SLICE39D_CONTENT_FAMILIES",
    "SLICE39D_DEFERRED_SCOPE",
    "SLICE39D_PERMANENT_BOUNDARIES",
    "SLICE39D_PROFILE_VERSION",
    "SLICE39D_SCHEMA_VERSION",
    "SLICE39D_SPEC_ID",
    "SLICE39D_SPEC_VERSION",
    "CandidateCommunicativePurpose",
    "CandidateReferentReference",
    "CandidateRequestedActDescription",
    "CandidateSemanticContentAssembly",
    "CandidateSemanticContentAssemblyResult",
    "CandidateSemanticContentCanonicalizationError",
    "CandidateSemanticContentPayload",
    "CandidateSemanticContentProfileIdentity",
    "CandidateSemanticContentStatus",
    "CandidateSemanticContentValidationCode",
    "CandidateSemanticContentValidationError",
    "CandidateSemanticContentValidationIssue",
    "CandidateSemanticContentValidationReport",
    "CandidateSemanticDistinction",
    "CandidateSemanticRelationReference",
    "CommunicativeForceCandidate",
    "ReferentCandidateKind",
    "SemanticDistinctionKind",
    "assemble_candidate_semantic_content",
    "assert_valid_assembly",
    "assert_valid_assembly_result",
    "canonical_field_order",
    "canonical_json_bytes",
    "canonical_record_mapping_39d",
    "deterministic_digest",
    "deterministic_record_digest",
    "expected_assembly_digest",
    "expected_assembly_id",
    "expected_communicative_purpose_id",
    "expected_distinction_id",
    "expected_payload_id",
    "expected_profile_id",
    "expected_referent_id",
    "expected_requested_act_id",
    "expected_result_id",
    "expected_semantic_relation_reference_id",
    "make_semantic_relation_candidate_reference",
    "stable_identifier",
    "validate_assembly",
    "validate_assembly_result",
    "validate_communicative_purpose",
    "validate_distinction",
    "validate_payload",
    "validate_profile",
    "validate_referent_reference",
    "validate_requested_act",
    "validate_semantic_relation_reference",
    "with_expected_assembly_identity",
    "with_expected_id",
)
