"""Slice 39D candidate-only semantic-content authority boundaries."""

from __future__ import annotations

SLICE39D_CONTENT_FAMILIES = (
    "communicative_purpose",
    "communicative_force_candidates",
    "requested_act_description",
    "concept_candidate_references",
    "sense_candidate_references",
    "semantic_relation_candidate_references",
    "action_root_candidate_references",
    "predicate_candidate_references",
    "frame_candidate_references",
    "role_layout_candidate_references",
    "referent_candidate_references",
    "source_and_comparison_target_references",
    "conditions",
    "negation",
    "qualification",
    "temporal_distinctions",
    "status_distinctions",
    "scope",
    "attachments",
    "limitations",
    "missing_information",
    "conflicting_information",
    "authority_sensitive_implications",
    "effect_boundary_references",
    "capability_family_candidate_references",
)

SLICE39D_PERMANENT_BOUNDARIES = (
    "candidate semantic content is not selected meaning",
    "communicative force candidate is not gate disposition",
    "requested act description is not permission or authorization",
    "concept candidate reference is not selected concept",
    "sense candidate reference is not selected sense",
    "semantic relation reference is not a relation fact",
    "semantic relation reference is not truth",
    "action-root candidate is not selected predicate",
    "predicate candidate is not selected predicate",
    "frame candidate is not selected frame",
    "role-layout candidate is not participant assignment",
    "referent candidate is not resolved referent",
    "source reference is not source reliability",
    "comparison-target reference is not comparison execution",
    "missing information is not a clarification decision",
    "missing information does not emit a clarification question",
    "conflicting information is not refusal",
    "effect boundary is not permission",
    "capability-family reference is not capability availability",
    "capability-family reference is not route or invocation",
    "candidate assembly is not ranking or selection",
    "candidate assembly is not evidence validation",
    "candidate assembly is not truth determination",
    "candidate assembly performs no filesystem, network, memory, tool, action, rendering, or delivery effect",
)

SLICE39D_DEFERRED_SCOPE = (
    "candidate-set and alternative preservation",
    "candidate ranking",
    "candidate selection",
    "verbal cognition gate evaluation",
    "clarification question emission",
    "refusal and blocked progression",
    "selected governed meaning",
    "truth determination",
    "evidence validation",
    "permission",
    "capability availability",
    "route creation",
    "invocation proposal or execution",
    "tool use",
    "action execution",
    "memory access",
    "rendering",
    "delivery",
)

__all__ = (
    "SLICE39D_CONTENT_FAMILIES",
    "SLICE39D_DEFERRED_SCOPE",
    "SLICE39D_PERMANENT_BOUNDARIES",
)
