"""Slice 24 immutable authority data.

Only exact passed scope may be accepted. This module is data-only.
"""

from __future__ import annotations

SLICE24_VERSION = "slice24-full-regression-acceptance-bundle-scaffold-v1"
SLICE24_TITLE = "Full Regression and Acceptance Bundle Scaffold"

REQUIRED_FORGE_REPO = "/home/nic/forge"
REQUIRED_FORGE_BRANCH = "main"
REQUIRED_FORGE_HEAD_BEFORE_SLICE24 = "0cf8829d08809658e2bcc4dcfd8497c5ae7320c5"
REQUIRED_FORGE_HEAD_SUBJECT_BEFORE_SLICE24 = "Slice 23 end-to-end dry-run harness scaffold"

REQUIRED_AIWEB_REPO = "/home/nic/aiweb"
REQUIRED_AIWEB_HEAD_SLICE22 = "0df0eaff8d23c4df18851540e221b79231f30e8f"
REQUIRED_AIWEB_SUBJECT_SLICE22 = "Slice 22 operator console evidence view"

MATRIX_VERSION = 'slice24-design-v1'
ACCEPTANCE_RULE = 'Overall PASS requires every required active verifier/test/context/source-guard to pass. Any fail or missing required check means no accepted broad scope. Historical or unrelated paths must be classified with reason, never silently ignored.'
BROAD_CLAIM_RULE = 'The accepted-scope record may only claim exact passed scope. It must not claim general-language competence or live runtime authority.'

REQUIRED_BEHAVIOR_TESTS = [{'command': ['/usr/bin/python3', 'scripts/test_aiweb_slice01_proof_scaffold.py'],
  'path': 'scripts/test_aiweb_slice01_proof_scaffold.py',
  'required': True,
  'slice': 1},
 {'command': ['/usr/bin/python3', 'scripts/test_aiweb_slice02_gp014_regression_scaffold.py'],
  'path': 'scripts/test_aiweb_slice02_gp014_regression_scaffold.py',
  'required': True,
  'slice': 2},
 {'command': ['/usr/bin/python3',
              'scripts/test_aiweb_slice03_status_claim_scaffold.py',
              '/home/nic/forge'],
  'path': 'scripts/test_aiweb_slice03_status_claim_scaffold.py',
  'required': True,
  'slice': 3},
 {'command': ['/usr/bin/python3',
              'scripts/test_aiweb_slice04_decision_baseline_scaffold.py',
              '/home/nic/forge'],
  'path': 'scripts/test_aiweb_slice04_decision_baseline_scaffold.py',
  'required': True,
  'slice': 4},
 {'command': ['/usr/bin/python3', 'scripts/test_aiweb_slice05_implementation_ledger_scaffold.py'],
  'path': 'scripts/test_aiweb_slice05_implementation_ledger_scaffold.py',
  'required': True,
  'slice': 5},
 {'command': ['/usr/bin/python3', 'scripts/test_aiweb_slice06_authority_scanner_scaffold.py'],
  'path': 'scripts/test_aiweb_slice06_authority_scanner_scaffold.py',
  'required': True,
  'slice': 6},
 {'command': ['/usr/bin/python3', 'scripts/test_aiweb_slice07_meaning_law_trace_scaffold.py'],
  'path': 'scripts/test_aiweb_slice07_meaning_law_trace_scaffold.py',
  'required': True,
  'slice': 7},
 {'command': ['/usr/bin/python3', 'scripts/test_aiweb_slice08_concept_boundary_scaffold.py'],
  'path': 'scripts/test_aiweb_slice08_concept_boundary_scaffold.py',
  'required': True,
  'slice': 8},
 {'command': ['/usr/bin/python3', 'scripts/test_aiweb_slice09_predicate_role_boundary_scaffold.py'],
  'path': 'scripts/test_aiweb_slice09_predicate_role_boundary_scaffold.py',
  'required': True,
  'slice': 9},
 {'command': ['/usr/bin/python3',
              'scripts/test_aiweb_slice10_verbal_cognition_gate_boundary_scaffold.py'],
  'path': 'scripts/test_aiweb_slice10_verbal_cognition_gate_boundary_scaffold.py',
  'required': True,
  'slice': 10},
 {'command': ['/usr/bin/python3',
              'scripts/test_aiweb_slice11_candidate_meaning_boundary_scaffold.py'],
  'path': 'scripts/test_aiweb_slice11_candidate_meaning_boundary_scaffold.py',
  'required': True,
  'slice': 11},
 {'command': ['/usr/bin/python3',
              'scripts/test_aiweb_slice12_ambiguity_clarification_boundary_scaffold.py'],
  'path': 'scripts/test_aiweb_slice12_ambiguity_clarification_boundary_scaffold.py',
  'required': True,
  'slice': 12},
 {'command': ['/usr/bin/python3',
              'scripts/test_aiweb_slice13_requirements_traceability_scaffold.py'],
  'path': 'scripts/test_aiweb_slice13_requirements_traceability_scaffold.py',
  'required': True,
  'slice': 13},
 {'command': ['/usr/bin/python3',
              'scripts/test_aiweb_slice14_external_resource_quarantine_scaffold.py'],
  'path': 'scripts/test_aiweb_slice14_external_resource_quarantine_scaffold.py',
  'required': True,
  'slice': 14},
 {'command': ['/usr/bin/python3',
              'scripts/test_aiweb_slice15_corpus_evidence_memory_trace_scaffold.py'],
  'path': 'scripts/test_aiweb_slice15_corpus_evidence_memory_trace_scaffold.py',
  'required': True,
  'slice': 15},
 {'command': ['/usr/bin/python3',
              'scripts/test_aiweb_slice16_selected_meaning_boundary_scaffold.py',
              '/home/nic/forge'],
  'path': 'scripts/test_aiweb_slice16_selected_meaning_boundary_scaffold.py',
  'required': True,
  'slice': 16},
 {'command': ['/usr/bin/python3',
              'scripts/test_aiweb_slice17_output_expression_boundary_scaffold.py',
              '/home/nic/forge'],
  'path': 'scripts/test_aiweb_slice17_output_expression_boundary_scaffold.py',
  'required': True,
  'slice': 17},
 {'command': ['/usr/bin/python3',
              'scripts/test_aiweb_slice18_gp014_preservation_decision_scaffold.py',
              '/home/nic/forge'],
  'path': 'scripts/test_aiweb_slice18_gp014_preservation_decision_scaffold.py',
  'required': True,
  'slice': 18},
 {'command': ['/usr/bin/python3',
              'scripts/test_aiweb_slice18_gp014_preservation_decision_verify_contexts.py'],
  'path': 'scripts/test_aiweb_slice18_gp014_preservation_decision_verify_contexts.py',
  'required': True,
  'slice': 18},
 {'command': ['/usr/bin/python3', 'scripts/test_aiweb_slice19_rmc_echo_boundary_scaffold.py'],
  'path': 'scripts/test_aiweb_slice19_rmc_echo_boundary_scaffold.py',
  'required': True,
  'slice': 19},
 {'command': ['/usr/bin/python3',
              'scripts/test_aiweb_slice20_delivery_action_tool_routing_boundary_scaffold.py'],
  'path': 'scripts/test_aiweb_slice20_delivery_action_tool_routing_boundary_scaffold.py',
  'required': True,
  'slice': 20},
 {'command': ['/usr/bin/python3',
              'scripts/test_aiweb_slice21_read_only_inspection_surface_scaffold.py'],
  'path': 'scripts/test_aiweb_slice21_read_only_inspection_surface_scaffold.py',
  'required': True,
  'slice': 21},
 {'command': ['/usr/bin/python3',
              'scripts/test_aiweb_slice23_end_to_end_dry_run_harness_scaffold.py'],
  'path': 'scripts/test_aiweb_slice23_end_to_end_dry_run_harness_scaffold.py',
  'required': True,
  'slice': 23}]

REQUIRED_SLICE_VERIFIERS = [{'command': ['/usr/bin/python3',
              'scripts/aiweb_slice01_proof_scaffold_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice01_proof_scaffold_verify.py',
  'required': True,
  'slice': 1},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice02_gp014_regression_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice02_gp014_regression_verify.py',
  'required': True,
  'slice': 2},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice03_status_claim_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice03_status_claim_verify.py',
  'required': True,
  'slice': 3},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice04_decision_baseline_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice04_decision_baseline_verify.py',
  'required': True,
  'slice': 4},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice05_implementation_ledger_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice05_implementation_ledger_verify.py',
  'required': True,
  'slice': 5},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice06_authority_scanner_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice06_authority_scanner_verify.py',
  'required': True,
  'slice': 6},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice07_meaning_law_trace_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice07_meaning_law_trace_verify.py',
  'required': True,
  'slice': 7},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice08_concept_boundary_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice08_concept_boundary_verify.py',
  'required': True,
  'slice': 8},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice09_predicate_role_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice09_predicate_role_verify.py',
  'required': True,
  'slice': 9},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice10_verbal_cognition_gate_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice10_verbal_cognition_gate_verify.py',
  'required': True,
  'slice': 10},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice11_candidate_meaning_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice11_candidate_meaning_verify.py',
  'required': True,
  'slice': 11},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice12_ambiguity_clarification_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice12_ambiguity_clarification_verify.py',
  'required': True,
  'slice': 12},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice13_requirements_traceability_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice13_requirements_traceability_verify.py',
  'required': True,
  'slice': 13},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice14_external_resource_quarantine_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice14_external_resource_quarantine_verify.py',
  'required': True,
  'slice': 14},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice15_corpus_evidence_memory_trace_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice15_corpus_evidence_memory_trace_verify.py',
  'required': True,
  'slice': 15},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice16_selected_meaning_boundary_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice16_selected_meaning_boundary_verify.py',
  'required': True,
  'slice': 16},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice17_output_expression_boundary_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice17_output_expression_boundary_verify.py',
  'required': True,
  'slice': 17},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice18_gp014_preservation_decision_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice18_gp014_preservation_decision_verify.py',
  'required': True,
  'slice': 18},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice19_rmc_echo_boundary_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice19_rmc_echo_boundary_verify.py',
  'required': True,
  'slice': 19},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice20_delivery_action_tool_routing_boundary_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice20_delivery_action_tool_routing_boundary_verify.py',
  'required': True,
  'slice': 20},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice21_read_only_inspection_surface_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice21_read_only_inspection_surface_verify.py',
  'required': True,
  'slice': 21},
 {'command': ['/usr/bin/python3',
              'scripts/aiweb_slice23_end_to_end_dry_run_harness_verify.py',
              '/home/nic/forge'],
  'path': 'scripts/aiweb_slice23_end_to_end_dry_run_harness_verify.py',
  'required': True,
  'slice': 23}]

REQUIRED_EXTERNAL_CONTEXT_CHECKS = [{'acceptance_rule': 'required context check for full Slice 1-23 acceptance; if repo is absent or '
                     'focused paths are dirty, Slice 24 overall verdict must fail or classify '
                     'scope as incomplete.',
  'exact_paths': ['apps/forge-operator-console/docs/SLICE22_OPERATOR_CONSOLE_EVIDENCE_VIEW.md',
                  'apps/forge-operator-console/scripts/verify_slice22_evidence_view.py',
                  'apps/forge-operator-console/src/App.tsx',
                  'apps/forge-operator-console/src/api/forgeClient.ts',
                  'apps/forge-operator-console/src/api/types.ts',
                  'apps/forge-operator-console/src/shell/TopTabs.tsx',
                  'apps/forge-operator-console/src/styles/theme.css',
                  'apps/forge-operator-console/src/tabs/EvidenceViewTab.tsx'],
  'kind': 'external_context_check_not_forge_source',
  'repo': '/home/nic/aiweb',
  'required_head': '0df0eaff8d23c4df18851540e221b79231f30e8f',
  'required_subject': 'Slice 22 operator console evidence view',
  'slice': 22}]

REQUIRED_SOURCE_GUARDS = [{'guard': 'forge_working_tree_clean_for_acceptance', 'required': True},
 {'guard': 'no_python_cache_before_or_after_run', 'required': True},
 {'guard': 'no_staged_files_for_acceptance_run', 'required': True},
 {'guard': 'slice24_files_have_no_model_network_memory_delivery_action_authority',
  'required': True},
 {'guard': 'historical_backup_paths_classified_not_executed_as_active_authority', 'required': True},
 {'guard': 'every cataloged verifier_like_path_receives_classification', 'required': True}]

CLASSIFICATION_POLICY = {'classes': {'HISTORICAL_BACKUP_NOT_ACTIVE_AUTHORITY': 'anything under backups/',
             'MEMORY_ARCHIVE_NOT_ACTIVE_AUTHORITY': 'anything under memory/ unless explicitly '
                                                    'named as current accepted-scope support '
                                                    'record',
             'PATCH_ERA_SUPPORTING_NOT_LANGUAGE_CORE_ACCEPTANCE': 'scripts/patch*, general '
                                                                  'pipeline and legacy patch-era '
                                                                  'verifiers not directly part of '
                                                                  'Slice 1-23 language-core '
                                                                  'acceptance',
             'REQUIRED_ACTIVE_BEHAVIOR_TEST': 'scripts/test_aiweb_sliceNN_* behavior test for '
                                              'active slices 1-21 and 23, including Slice 18 '
                                              'verifier context behavior test',
             'REQUIRED_ACTIVE_SLICE_VERIFIER': 'scripts/aiweb_sliceNN_* verifier for active slices '
                                               '1-21 and 23',
             'REQUIRED_EXTERNAL_CONTEXT_CHECK': 'Slice 22 AI.Web operator-console context check; '
                                                'not Forge source',
             'REQUIRED_SOURCE_GUARD': 'repository cleanliness, pycache absence, no '
                                      'model/network/memory/action authority in Slice24 patch',
             'SUPPORTING_EVIDENCE_NOT_EXECUTED': 'README, receipt, manifest, proof surface, or '
                                                 'config evidence read/cataloged but not '
                                                 'executable',
             'UNCLASSIFIED_BLOCKER': 'any verifier/test/receipt-like path not matching a policy '
                                     'class; overall design should fail until classified'},
 'hard_rule': 'No cataloged verifier/test/proof-like path may disappear. It must be required, '
              'supporting, historical, or blocker-classified with reason.',
 'policy_version': 'slice24-classification-v1'}

SLICE24_HARD_BOUNDARY = (
    "only_exact_passed_scope_is_accepted",
    "no_broad_general_language_claim_without_full_required_proof_set",
    "no_live_runtime_claim",
    "no_memory_write",
    "no_external_resource_promotion",
    "no_delivery",
    "no_action_execution",
    "no_route_or_config_or_ui_authority_change",
)

ACCEPTED_SCOPE_SENTENCE = (
    "Only the exact Slice 1-23 required verifier/test/context/source-guard "
    "surfaces that passed in this recorded local context are accepted."
)

PROHIBITED_ACCEPTANCE_CLAIMS = (
    "Forge understands general language",
    "general language is accepted",
    "live runtime authority is accepted",
    "public capability is accepted",
    "memory writes are accepted",
    "delivery is accepted",
    "actions are accepted",
    "tool invocation is accepted",
)

SLICE24_PATCH_FILES = ['aiweb_full_regression_acceptance_bundle_scaffold/__init__.py',
 'aiweb_full_regression_acceptance_bundle_scaffold/authority.py',
 'aiweb_full_regression_acceptance_bundle_scaffold/catalog.py',
 'aiweb_full_regression_acceptance_bundle_scaffold/classification.py',
 'aiweb_full_regression_acceptance_bundle_scaffold/context.py',
 'aiweb_full_regression_acceptance_bundle_scaffold/runner.py',
 'aiweb_full_regression_acceptance_bundle_scaffold/receipt.py',
 'aiweb_full_regression_acceptance_bundle_scaffold/scope.py',
 'aiweb_full_regression_acceptance_bundle_scaffold/source_guard.py',
 'aiweb_full_regression_acceptance_bundle_scaffold/verify.py',
 'scripts/README_aiweb_slice24_full_regression_acceptance_bundle_scaffold.md',
 'scripts/aiweb_slice24_full_regression_acceptance_bundle_verify.py',
 'scripts/test_aiweb_slice24_full_regression_acceptance_bundle_scaffold.py']

# Built by string concatenation so the source guard can detect concrete import or call
# fragments without this authority file containing those fragments contiguously.
FORBIDDEN_NETWORK_OR_MODEL_FRAGMENTS = (
    "open" + "ai.",
    "anth" + "ropic.",
    "oll" + "ama.",
    "lang" + "chain",
    "ll" + "ama_index",
    "requests" + ".",
    "http" + "x.",
    "urllib" + ".request",
    "socket" + ".",
    "os" + ".system",
    "shell" + "=True",
)

ALLOWED_SUBPROCESS_FILES = (
    "aiweb_full_regression_acceptance_bundle_scaffold/context.py",
    "aiweb_full_regression_acceptance_bundle_scaffold/runner.py",
)
