"""Public Slice 37G disabled structural-to-concept bootstrap surface.

Importing this package activates nothing. Execution requires an explicit exact
fixture invocation and an explicitly enabled offline integration state.
"""

from .fixtures import (
    FIXTURE_AMBIGUOUS,
    FIXTURE_NO_MATCH,
    FIXTURE_ONE_TO_ONE,
    FIXTURE_UNMAPPED,
    FIXTURE_UNSUPPORTED,
    get_disabled_structural_concept_fixture,
    is_exact_accepted_fixture,
    list_disabled_structural_concept_fixtures,
)
from .integration import (
    REASON_DISABLED,
    REQUESTED_OPERATION,
    build_disabled_structural_concept_bootstrap_state,
    build_fixture_invocation,
    build_slice37_acceptance_record,
    build_slice37_rollback_metadata,
    run_disabled_structural_concept_bootstrap,
)
from .schema import (
    PRE_SLICE37_COMMIT,
    PRE_SLICE37_TREE,
    SLICE37_ACCEPTED_CHAIN,
    SLICE37_ACCEPTED_SCOPE,
    SLICE37_DEFERRED_SCOPE,
    SLICE37_INCREMENT_LABELS,
    SLICE37_PERMANENT_BOUNDARIES,
    SLICE37F_ACCEPTED_HEAD,
    SLICE37F_ACCEPTED_SUBJECT,
    SLICE37F_ACCEPTED_TREE,
    SLICE37G_COMMIT_SUBJECT,
    SLICE37G_SCHEMA_VERSION,
    SLICE37G_SPEC_ID,
    SLICE37G_SPEC_VERSION,
    DisabledStructuralConceptBootstrapResult,
    DisabledStructuralConceptBootstrapState,
    DisabledStructuralConceptFixture,
    DisabledStructuralConceptInvocation,
    IntegrationStage,
    IntegrationStageReceipt,
    IntegrationStatus,
    Slice37AcceptanceRecord,
    Slice37RollbackMetadata,
)
from .validation import (
    ValidationReport,
    validate_acceptance_record,
    validate_fixture,
    validate_integration_result,
    validate_integration_state,
    validate_invocation,
    validate_rollback_metadata,
    validate_stage_receipt,
)

__all__ = (
    "PRE_SLICE37_COMMIT",
    "PRE_SLICE37_TREE",
    "SLICE37_ACCEPTED_CHAIN",
    "SLICE37_ACCEPTED_SCOPE",
    "SLICE37_DEFERRED_SCOPE",
    "SLICE37_INCREMENT_LABELS",
    "SLICE37_PERMANENT_BOUNDARIES",
    "SLICE37F_ACCEPTED_HEAD",
    "SLICE37F_ACCEPTED_SUBJECT",
    "SLICE37F_ACCEPTED_TREE",
    "SLICE37G_COMMIT_SUBJECT",
    "SLICE37G_SCHEMA_VERSION",
    "SLICE37G_SPEC_ID",
    "SLICE37G_SPEC_VERSION",
    "DisabledStructuralConceptBootstrapResult",
    "DisabledStructuralConceptBootstrapState",
    "DisabledStructuralConceptFixture",
    "DisabledStructuralConceptInvocation",
    "FIXTURE_AMBIGUOUS",
    "FIXTURE_NO_MATCH",
    "FIXTURE_ONE_TO_ONE",
    "FIXTURE_UNMAPPED",
    "FIXTURE_UNSUPPORTED",
    "IntegrationStage",
    "IntegrationStageReceipt",
    "IntegrationStatus",
    "REASON_DISABLED",
    "REQUESTED_OPERATION",
    "Slice37AcceptanceRecord",
    "Slice37RollbackMetadata",
    "ValidationReport",
    "build_disabled_structural_concept_bootstrap_state",
    "build_fixture_invocation",
    "build_slice37_acceptance_record",
    "build_slice37_rollback_metadata",
    "get_disabled_structural_concept_fixture",
    "is_exact_accepted_fixture",
    "list_disabled_structural_concept_fixtures",
    "run_disabled_structural_concept_bootstrap",
    "validate_acceptance_record",
    "validate_fixture",
    "validate_integration_result",
    "validate_integration_state",
    "validate_invocation",
    "validate_rollback_metadata",
    "validate_stage_receipt",
)
