"""Explicit Slice 37B validation, identity, and lifecycle-law surface.

Importing this package registers nothing and performs no validation, lookup,
transition, persistence, routing, or runtime activation.  Callers must construct
exact immutable records and invoke the exported pure validators explicitly.
"""

from .collection import assert_governance_batch, validate_governance_batch
from .identity import (
    expected_resource_lineage_id,
    parse_resource_version,
    recompute_resource_id,
    resource_id,
    resource_identity_field,
    resource_lineage_body,
    version_advances,
    with_expected_authority_id,
    with_expected_batch_id,
    with_expected_transition_id,
    with_recomputed_resource_id,
)
from .lifecycle import assert_lifecycle_transition, evaluate_lifecycle_transition
from .rules import CONCEPT_LIFECYCLE_TRANSITION_RULES, transition_rule
from .schema import (
    SLICE37B_ACCEPTED_PARENT_HEAD,
    SLICE37B_ACCEPTED_PARENT_SUBJECT,
    SLICE37B_ACCEPTED_PARENT_TREE,
    SLICE37B_SCHEMA_VERSION,
    SLICE37B_SPEC_ID,
    SLICE37B_SPEC_VERSION,
    ConceptGovernanceBatch,
    ConceptGovernanceValidationCode,
    ConceptGovernanceValidationError,
    ConceptGovernanceValidationIssue,
    ConceptGovernanceValidationReport,
    ConceptLifecycleAuthorityRecord,
    ConceptLifecycleTransitionDecision,
    ConceptLifecycleTransitionKind,
    ConceptLifecycleTransitionRecord,
    ConceptLifecycleTransitionRule,
    GovernedConceptResource,
)
from .validation import (
    active_lifecycle_states,
    nonoperative_lifecycle_states,
    report_from_issues,
    resource_scope_tokens,
    sorted_issues,
    validate_governance_batch_shape,
    validate_governed_resource,
    validate_lifecycle_authority_record,
    validate_namespace_key,
    validate_provenance_record,
)

__all__ = (
    "CONCEPT_LIFECYCLE_TRANSITION_RULES",
    "SLICE37B_ACCEPTED_PARENT_HEAD",
    "SLICE37B_ACCEPTED_PARENT_SUBJECT",
    "SLICE37B_ACCEPTED_PARENT_TREE",
    "SLICE37B_SCHEMA_VERSION",
    "SLICE37B_SPEC_ID",
    "SLICE37B_SPEC_VERSION",
    "ConceptGovernanceBatch",
    "ConceptGovernanceValidationCode",
    "ConceptGovernanceValidationError",
    "ConceptGovernanceValidationIssue",
    "ConceptGovernanceValidationReport",
    "ConceptLifecycleAuthorityRecord",
    "ConceptLifecycleTransitionDecision",
    "ConceptLifecycleTransitionKind",
    "ConceptLifecycleTransitionRecord",
    "ConceptLifecycleTransitionRule",
    "GovernedConceptResource",
    "active_lifecycle_states",
    "assert_governance_batch",
    "assert_lifecycle_transition",
    "evaluate_lifecycle_transition",
    "expected_resource_lineage_id",
    "nonoperative_lifecycle_states",
    "parse_resource_version",
    "recompute_resource_id",
    "report_from_issues",
    "resource_id",
    "resource_identity_field",
    "resource_lineage_body",
    "resource_scope_tokens",
    "sorted_issues",
    "transition_rule",
    "validate_governance_batch",
    "validate_governance_batch_shape",
    "validate_governed_resource",
    "validate_lifecycle_authority_record",
    "validate_namespace_key",
    "validate_provenance_record",
    "version_advances",
    "with_expected_authority_id",
    "with_expected_batch_id",
    "with_expected_transition_id",
    "with_recomputed_resource_id",
)
