"""AI.Web Slice 38G predicate, role, and frame candidate proposal.

This package connects accepted Slice 37F concept/sense proposals to exact,
governed Slice 38 registry identities.  It creates candidate records only.
It does not select meaning, grant permission, create routes, invoke tools,
perform actions, access memory, deliver output, validate evidence, or decide
truth.
"""

from .authority import (
    CANONICAL_COMPATIBILITY_CONFLICT_KEYS,
    CANONICAL_COMPATIBILITY_RULE_KEYS,
    CANONICAL_COMPATIBILITY_RULING,
    CANONICAL_PROVENANCE_REFS,
    SLICE38G_NON_AUTHORITY_BOUNDARIES,
)
from .compatibility import (
    CANONICAL_COMPATIBILITY_SNAPSHOT,
    build_compatibility_conflict,
    build_compatibility_snapshot,
    build_exact_compatibility_rule,
)
from .proposal import propose_predicate_role_frame_candidates
from .records import (
    DEFAULT_PROPOSAL_PROFILE,
    SLICE38_REGISTRY_SNAPSHOT,
    build_default_predicate_role_frame_proposal_profile,
)
from .schema import (
    ACTION_PREDICATE_CANDIDATE_SCHEMA_ID,
    CAPABILITY_REFERENCE_CANDIDATE_SCHEMA_ID,
    COMPATIBILITY_CONFLICT_SCHEMA_ID,
    COMPATIBILITY_RULE_SCHEMA_ID,
    COMPATIBILITY_SNAPSHOT_SCHEMA_ID,
    PROFILE_SCHEMA_ID,
    RESULT_SCHEMA_ID,
    ROLE_LAYOUT_CANDIDATE_SCHEMA_ID,
    SLICE38G_ACCEPTED_PARENT_HEAD,
    SLICE38G_ACCEPTED_PARENT_SUBJECT,
    SLICE38G_ACCEPTED_PARENT_TREE,
    SLICE38G_SCHEMA_VERSION,
    SLICE38G_SPEC_ID,
    SLICE38G_SPEC_VERSION,
    SLICE38_SNAPSHOT_SCHEMA_ID,
    ActionRootCompatibilityConflict,
    ActionRootCompatibilityRule,
    ActionRootPredicateCandidate,
    CandidateProposalStatus,
    CandidateStructuralState,
    CandidateValidationCode,
    CandidateValidationError,
    CandidateValidationIssue,
    CandidateValidationReport,
    CapabilityReferenceCandidate,
    CompatibilityLifecycleState,
    CompatibilityMatchMode,
    CompatibilityRegistrySnapshot,
    PredicateRoleFrameCandidateProposalResult,
    PredicateRoleFrameProposalProfile,
    RoleLayoutCandidate,
    Slice38RegistrySnapshotIdentity,
)
from .snapshot import build_slice38_registry_snapshot
from .validation import (
    PUBLIC_VALIDATORS,
    assert_valid_result,
    validate_action_candidate,
    validate_capability_candidate,
    validate_compatibility_snapshot,
    validate_conflict,
    validate_profile,
    validate_result,
    validate_role_layout_candidate,
    validate_rule,
    validate_slice38_snapshot,
)

__all__ = (
    "ACTION_PREDICATE_CANDIDATE_SCHEMA_ID",
    "CAPABILITY_REFERENCE_CANDIDATE_SCHEMA_ID",
    "CANONICAL_COMPATIBILITY_CONFLICT_KEYS",
    "CANONICAL_COMPATIBILITY_RULE_KEYS",
    "CANONICAL_COMPATIBILITY_RULING",
    "CANONICAL_COMPATIBILITY_SNAPSHOT",
    "CANONICAL_PROVENANCE_REFS",
    "COMPATIBILITY_CONFLICT_SCHEMA_ID",
    "COMPATIBILITY_RULE_SCHEMA_ID",
    "COMPATIBILITY_SNAPSHOT_SCHEMA_ID",
    "DEFAULT_PROPOSAL_PROFILE",
    "PROFILE_SCHEMA_ID",
    "PUBLIC_VALIDATORS",
    "RESULT_SCHEMA_ID",
    "ROLE_LAYOUT_CANDIDATE_SCHEMA_ID",
    "SLICE38G_ACCEPTED_PARENT_HEAD",
    "SLICE38G_ACCEPTED_PARENT_SUBJECT",
    "SLICE38G_ACCEPTED_PARENT_TREE",
    "SLICE38G_NON_AUTHORITY_BOUNDARIES",
    "SLICE38G_SCHEMA_VERSION",
    "SLICE38G_SPEC_ID",
    "SLICE38G_SPEC_VERSION",
    "SLICE38_REGISTRY_SNAPSHOT",
    "SLICE38_SNAPSHOT_SCHEMA_ID",
    "ActionRootCompatibilityConflict",
    "ActionRootCompatibilityRule",
    "ActionRootPredicateCandidate",
    "CandidateProposalStatus",
    "CandidateStructuralState",
    "CandidateValidationCode",
    "CandidateValidationError",
    "CandidateValidationIssue",
    "CandidateValidationReport",
    "CapabilityReferenceCandidate",
    "CompatibilityLifecycleState",
    "CompatibilityMatchMode",
    "CompatibilityRegistrySnapshot",
    "PredicateRoleFrameCandidateProposalResult",
    "PredicateRoleFrameProposalProfile",
    "RoleLayoutCandidate",
    "Slice38RegistrySnapshotIdentity",
    "assert_valid_result",
    "build_compatibility_conflict",
    "build_compatibility_snapshot",
    "build_default_predicate_role_frame_proposal_profile",
    "build_exact_compatibility_rule",
    "build_slice38_registry_snapshot",
    "propose_predicate_role_frame_candidates",
    "validate_action_candidate",
    "validate_capability_candidate",
    "validate_compatibility_snapshot",
    "validate_conflict",
    "validate_profile",
    "validate_result",
    "validate_role_layout_candidate",
    "validate_rule",
    "validate_slice38_snapshot",
)
