"""Slice 39A candidate-meaning core schema exports."""

from .authority import (
    CONSTRUCTION_ONLY_STATUS_VALUES,
    DEFERRED_SLICE40_GATE_OUTCOMES,
    PERMANENT_CANDIDATE_MEANING_BOUNDARIES,
    PROHIBITED_AUTHORITY_PATHS,
)
from .identity import (
    ACCEPTED_PARENT_HEAD,
    ACCEPTED_PARENT_SUBJECT,
    ACCEPTED_PARENT_TREE,
    ALTERNATIVE_REFERENCE_SCHEMA_ID,
    CONSTRUCTION_RECEIPT_SCHEMA_ID,
    CONTENT_SCHEMA_ID,
    IDENTITY_SCHEMA_ID,
    PACKAGE_ID,
    PACKAGE_NAME,
    PROVENANCE_SCHEMA_ID,
    SCHEMA_ABBREVIATION,
    SCHEMA_NAME,
    SCHEMA_VERSION,
    SPEC_ID,
    SPEC_VERSION,
    STATE_SCHEMA_ID,
)
from .schema import (
    CandidateMeaningAlternativeReference,
    CandidateMeaningConstructionReceipt,
    CandidateMeaningConstructionStatus,
    CandidateMeaningContent,
    CandidateMeaningIdentity,
    CandidateMeaningProvenance,
    CandidateMeaningState,
)

__all__ = (
    "ACCEPTED_PARENT_HEAD",
    "ACCEPTED_PARENT_SUBJECT",
    "ACCEPTED_PARENT_TREE",
    "ALTERNATIVE_REFERENCE_SCHEMA_ID",
    "CONSTRUCTION_ONLY_STATUS_VALUES",
    "CONSTRUCTION_RECEIPT_SCHEMA_ID",
    "CONTENT_SCHEMA_ID",
    "CandidateMeaningAlternativeReference",
    "CandidateMeaningConstructionReceipt",
    "CandidateMeaningConstructionStatus",
    "CandidateMeaningContent",
    "CandidateMeaningIdentity",
    "CandidateMeaningProvenance",
    "CandidateMeaningState",
    "DEFERRED_SLICE40_GATE_OUTCOMES",
    "IDENTITY_SCHEMA_ID",
    "PACKAGE_ID",
    "PACKAGE_NAME",
    "PERMANENT_CANDIDATE_MEANING_BOUNDARIES",
    "PROHIBITED_AUTHORITY_PATHS",
    "PROVENANCE_SCHEMA_ID",
    "SCHEMA_ABBREVIATION",
    "SCHEMA_NAME",
    "SCHEMA_VERSION",
    "SPEC_ID",
    "SPEC_VERSION",
    "STATE_SCHEMA_ID",
)
