"""Slice 38C closed read-only built-in action-root registry.

Importing this package constructs immutable in-memory records only. It does not
inspect source language, map a surface verb, select a predicate occurrence,
assign roles, complete frames, route capabilities, access evidence or memory,
activate tools, execute actions, render output, deliver messages, or release
software.
"""

from .authority import (
    BUILT_IN_ACTION_ROOT_DEFINITIONS,
    BUILT_IN_ACTION_ROOT_KEYS,
    BUILT_IN_PREDICATE_KEYS,
    SLICE38C_ADDITIONAL_AUTHORITY_LIMITATIONS,
    SLICE38C_COMMON_PROHIBITED_USES,
    SLICE38C_DECISION_OWNER_REF,
    SLICE38C_DEFERRED_HIGHER_CONSEQUENCE_FAMILIES,
    SLICE38C_HUMAN_APPROVAL_REF,
    SLICE38C_NAMESPACE_KEY,
    BuiltInActionRootDefinition,
)
from .identity import registry_digest, with_expected_manifest_id
from .records import (
    ACTION_ROOT_HISTORIES,
    ADMITTED_ACTION_ROOTS,
    ADMITTED_PREDICATES,
    ALL_AUTHORITIES,
    ALL_RESOURCES,
    ALL_TRANSITIONS,
    CURRENT_NAMESPACE,
    GOVERNANCE_BATCH,
    NAMESPACE_HISTORY,
    PREDICATE_HISTORIES,
    PROVENANCE_RECORDS,
)
from .registry import (
    BUILT_IN_ACTION_ROOT_REGISTRY,
    action_root_by_id,
    action_root_by_key,
    all_admitted_action_roots,
    all_admitted_predicates,
    built_in_action_root_registry,
    contains_action_root_id,
    contains_predicate_id,
    current_namespace,
    predicate_by_id,
    predicate_by_key,
    predicate_for_action_root_id,
    registry_manifest,
)
from .schema import (
    SLICE38C_ACCEPTED_PARENT_HEAD,
    SLICE38C_ACCEPTED_PARENT_SUBJECT,
    SLICE38C_ACCEPTED_PARENT_TREE,
    SLICE38C_EXPECTED_ACTION_ROOT_COUNT,
    SLICE38C_EXPECTED_NAMESPACE_COUNT,
    SLICE38C_EXPECTED_PREDICATE_COUNT,
    SLICE38C_SCHEMA_VERSION,
    SLICE38C_SOURCE_AUTHORITY_PACKET_SHA256,
    SLICE38C_SPEC_ID,
    SLICE38C_SPEC_VERSION,
    BuiltInActionRootRegistry,
    BuiltInActionRootRegistryManifest,
    BuiltInActionRootRegistryValidationCode,
    BuiltInActionRootRegistryValidationError,
    BuiltInActionRootRegistryValidationIssue,
    BuiltInActionRootRegistryValidationReport,
)
from .validation import (
    assert_built_in_action_root_registry,
    validate_built_in_action_root_registry,
    validate_registry_manifest,
)

__all__ = (
    "ACTION_ROOT_HISTORIES",
    "ADMITTED_ACTION_ROOTS",
    "ADMITTED_PREDICATES",
    "ALL_AUTHORITIES",
    "ALL_RESOURCES",
    "ALL_TRANSITIONS",
    "BUILT_IN_ACTION_ROOT_DEFINITIONS",
    "BUILT_IN_ACTION_ROOT_KEYS",
    "BUILT_IN_ACTION_ROOT_REGISTRY",
    "BUILT_IN_PREDICATE_KEYS",
    "CURRENT_NAMESPACE",
    "GOVERNANCE_BATCH",
    "NAMESPACE_HISTORY",
    "PREDICATE_HISTORIES",
    "PROVENANCE_RECORDS",
    "SLICE38C_ACCEPTED_PARENT_HEAD",
    "SLICE38C_ACCEPTED_PARENT_SUBJECT",
    "SLICE38C_ACCEPTED_PARENT_TREE",
    "SLICE38C_ADDITIONAL_AUTHORITY_LIMITATIONS",
    "SLICE38C_COMMON_PROHIBITED_USES",
    "SLICE38C_DECISION_OWNER_REF",
    "SLICE38C_DEFERRED_HIGHER_CONSEQUENCE_FAMILIES",
    "SLICE38C_EXPECTED_ACTION_ROOT_COUNT",
    "SLICE38C_EXPECTED_NAMESPACE_COUNT",
    "SLICE38C_EXPECTED_PREDICATE_COUNT",
    "SLICE38C_HUMAN_APPROVAL_REF",
    "SLICE38C_NAMESPACE_KEY",
    "SLICE38C_SCHEMA_VERSION",
    "SLICE38C_SOURCE_AUTHORITY_PACKET_SHA256",
    "SLICE38C_SPEC_ID",
    "SLICE38C_SPEC_VERSION",
    "BuiltInActionRootDefinition",
    "BuiltInActionRootRegistry",
    "BuiltInActionRootRegistryManifest",
    "BuiltInActionRootRegistryValidationCode",
    "BuiltInActionRootRegistryValidationError",
    "BuiltInActionRootRegistryValidationIssue",
    "BuiltInActionRootRegistryValidationReport",
    "action_root_by_id",
    "action_root_by_key",
    "all_admitted_action_roots",
    "all_admitted_predicates",
    "assert_built_in_action_root_registry",
    "built_in_action_root_registry",
    "contains_action_root_id",
    "contains_predicate_id",
    "current_namespace",
    "predicate_by_id",
    "predicate_by_key",
    "predicate_for_action_root_id",
    "registry_digest",
    "registry_manifest",
    "validate_built_in_action_root_registry",
    "validate_registry_manifest",
    "with_expected_manifest_id",
)
