"""Slice 36C symbolic grammar-operator registry.

Explicit import only. Importing this package creates no proposal, source
binding, operator application, phase assignment, meaning, permission, memory,
route, tool, action, rendering, or delivery authority.
"""

from .proposal_contract import evaluate_grammar_operator_proposal
from .registry import (
    build_default_symbolic_grammar_operator_registry,
    grammar_operator_for_glyph,
    grammar_operator_for_key,
    grammar_operators_for_family,
)
from .schema import (
    CANONICAL_ROADMAP_AUTHORITY_REF,
    EXPECTED_FBSC_CANONICAL_OPERATOR_COUNT,
    EXPECTED_GRAMMAR_OPERATOR_COUNT,
    EXPECTED_REQUIRED_FAMILY_COUNT,
    FBSC_VOLUME_II_AUTHORITY_REF,
    GRAMMAR_OPERATOR_PROPOSAL_DECISION_SCHEMA_ID,
    GRAMMAR_OPERATOR_PROPOSAL_RULE_SCHEMA_ID,
    GRAMMAR_OPERATOR_PROPOSAL_SCHEMA_ID,
    GRAMMAR_OPERATOR_REGISTRY_SCHEMA_ID,
    GRAMMAR_OPERATOR_SCHEMA_ID,
    REGISTRY_SCHEMA_VERSION,
    REGISTRY_SPEC_ID,
    REGISTRY_SPEC_VERSION,
    REQUIRED_LANGUAGE_CORE_FAMILIES,
    RMC_LANGUAGE_LAW_AUTHORITY_REF,
    RSOC_CONTRACT_AUTHORITY_REF,
    SOURCE_FIELD_AUTHORITY_REF,
    GrammarOperatorCompatibilityStatus,
    GrammarOperatorCommutationStatus,
    GrammarOperatorDefinition,
    GrammarOperatorDriftEffectStatus,
    GrammarOperatorEffect,
    GrammarOperatorEntropyEffectStatus,
    GrammarOperatorFamily,
    GrammarOperatorMalformedBehavior,
    GrammarOperatorOrigin,
    GrammarOperatorPhaseAffinityStatus,
    GrammarOperatorProposalDecision,
    GrammarOperatorProposalRuleContract,
    GrammarOperatorRuntimeStatus,
    GrammarOperatorUncertaintyBehavior,
    GrammarOperatorUnsupportedBehavior,
    ProposalDecisionStatus,
    ProposalRuleRuntimeStatus,
    SymbolicGrammarOperatorRegistry,
)
from .validation import (
    validate_grammar_operator_definition,
    validate_grammar_operator_proposal_decision,
    validate_grammar_operator_proposal_rule_contract,
    validate_symbolic_grammar_operator_registry,
)

__all__ = (
    "CANONICAL_ROADMAP_AUTHORITY_REF",
    "EXPECTED_FBSC_CANONICAL_OPERATOR_COUNT",
    "EXPECTED_GRAMMAR_OPERATOR_COUNT",
    "EXPECTED_REQUIRED_FAMILY_COUNT",
    "FBSC_VOLUME_II_AUTHORITY_REF",
    "GRAMMAR_OPERATOR_PROPOSAL_DECISION_SCHEMA_ID",
    "GRAMMAR_OPERATOR_PROPOSAL_RULE_SCHEMA_ID",
    "GRAMMAR_OPERATOR_PROPOSAL_SCHEMA_ID",
    "GRAMMAR_OPERATOR_REGISTRY_SCHEMA_ID",
    "GRAMMAR_OPERATOR_SCHEMA_ID",
    "REGISTRY_SCHEMA_VERSION",
    "REGISTRY_SPEC_ID",
    "REGISTRY_SPEC_VERSION",
    "REQUIRED_LANGUAGE_CORE_FAMILIES",
    "RMC_LANGUAGE_LAW_AUTHORITY_REF",
    "RSOC_CONTRACT_AUTHORITY_REF",
    "SOURCE_FIELD_AUTHORITY_REF",
    "GrammarOperatorCompatibilityStatus",
    "GrammarOperatorCommutationStatus",
    "GrammarOperatorDefinition",
    "GrammarOperatorDriftEffectStatus",
    "GrammarOperatorEffect",
    "GrammarOperatorEntropyEffectStatus",
    "GrammarOperatorFamily",
    "GrammarOperatorMalformedBehavior",
    "GrammarOperatorOrigin",
    "GrammarOperatorPhaseAffinityStatus",
    "GrammarOperatorProposalDecision",
    "GrammarOperatorProposalRuleContract",
    "GrammarOperatorRuntimeStatus",
    "GrammarOperatorUncertaintyBehavior",
    "GrammarOperatorUnsupportedBehavior",
    "ProposalDecisionStatus",
    "ProposalRuleRuntimeStatus",
    "SymbolicGrammarOperatorRegistry",
    "build_default_symbolic_grammar_operator_registry",
    "evaluate_grammar_operator_proposal",
    "grammar_operator_for_glyph",
    "grammar_operator_for_key",
    "grammar_operators_for_family",
    "validate_grammar_operator_definition",
    "validate_grammar_operator_proposal_decision",
    "validate_grammar_operator_proposal_rule_contract",
    "validate_symbolic_grammar_operator_registry",
)
