"""Public Slice 37A controlled concept-authority schema surface.

The package is schema-only and has zero registry population. It preserves the
historical Slice 8 scaffold without importing it as runtime authority.
"""

from .authority import (
    build_slice37a_authority_profile,
    build_slice37a_schema_contract,
)
from .identity import with_expected_resource_id
from .schema import (
    CONCEPT_RESOURCE_PROHIBITED_AUTHORITIES,
    HISTORICAL_SLICE8_COMMIT,
    HISTORICAL_SLICE8_SUBJECT,
    SLICE37A_ACCEPTED_PARENT_HEAD,
    SLICE37A_ACCEPTED_PARENT_SUBJECT,
    SLICE37A_ACCEPTED_PARENT_TREE,
    SLICE37A_DEFERRED_SCOPE,
    SLICE37A_SCHEMA_VERSION,
    SLICE37A_SPEC_ID,
    SLICE37A_SPEC_VERSION,
    ConceptAuthorityProfile,
    ConceptLifecycleState,
    ConceptNamespaceIdentity,
    ConceptProvenanceReference,
    ConceptRegistrySchemaContract,
    ConceptResourceKind,
    ControlledConceptIdentity,
    ControlledLexicalReference,
    ControlledSenseIdentity,
    LexicalReferenceKind,
    RelationDirection,
    SemanticClassIdentity,
    SemanticRelationFamilyIdentity,
    SemanticRelationTypeIdentity,
    TermConceptMappingIdentity,
)
from .validation import (
    ConceptSchemaValidationCode,
    ConceptSchemaValidationError,
    ConceptSchemaValidationIssue,
    ConceptSchemaValidationReport,
    validate_concept_authority_profile,
    validate_concept_namespace_identity,
    validate_concept_provenance_reference,
    validate_concept_registry_schema_contract,
    validate_controlled_concept_identity,
    validate_controlled_lexical_reference,
    validate_controlled_sense_identity,
    validate_semantic_class_identity,
    validate_semantic_relation_family_identity,
    validate_semantic_relation_type_identity,
    validate_term_concept_mapping_identity,
)

__all__ = (
    "CONCEPT_RESOURCE_PROHIBITED_AUTHORITIES",
    "HISTORICAL_SLICE8_COMMIT",
    "HISTORICAL_SLICE8_SUBJECT",
    "SLICE37A_ACCEPTED_PARENT_HEAD",
    "SLICE37A_ACCEPTED_PARENT_SUBJECT",
    "SLICE37A_ACCEPTED_PARENT_TREE",
    "SLICE37A_DEFERRED_SCOPE",
    "SLICE37A_SCHEMA_VERSION",
    "SLICE37A_SPEC_ID",
    "SLICE37A_SPEC_VERSION",
    "ConceptAuthorityProfile",
    "ConceptLifecycleState",
    "ConceptNamespaceIdentity",
    "ConceptProvenanceReference",
    "ConceptRegistrySchemaContract",
    "ConceptResourceKind",
    "ConceptSchemaValidationCode",
    "ConceptSchemaValidationError",
    "ConceptSchemaValidationIssue",
    "ConceptSchemaValidationReport",
    "ControlledConceptIdentity",
    "ControlledLexicalReference",
    "ControlledSenseIdentity",
    "LexicalReferenceKind",
    "RelationDirection",
    "SemanticClassIdentity",
    "SemanticRelationFamilyIdentity",
    "SemanticRelationTypeIdentity",
    "TermConceptMappingIdentity",
    "build_slice37a_authority_profile",
    "build_slice37a_schema_contract",
    "validate_concept_authority_profile",
    "validate_concept_namespace_identity",
    "validate_concept_provenance_reference",
    "validate_concept_registry_schema_contract",
    "validate_controlled_concept_identity",
    "validate_controlled_lexical_reference",
    "validate_controlled_sense_identity",
    "validate_semantic_class_identity",
    "validate_semantic_relation_family_identity",
    "validate_semantic_relation_type_identity",
    "validate_term_concept_mapping_identity",
    "with_expected_resource_id",
)
