"""Slice 36H disabled bounded structural bootstrap integration.

Importing this package creates no invocation and activates nothing. The only
runnable path requires an exact static fixture invocation and an explicit
offline enabled state.
"""

from .fixtures import (
    FIXTURE_GOVERNING,
    FIXTURE_INCOMPLETE_QUOTATION,
    FIXTURE_QUOTATION_CONFLICT,
    FIXTURE_ZERO_DERIVATION,
    get_bounded_structural_fixture,
    is_exact_accepted_bounded_structural_fixture,
    list_bounded_structural_fixtures,
)
from .integration import (
    REASON_COMPLETED_CANDIDATES,
    REASON_COMPLETED_NON_PROGRESS,
    REASON_DISABLED,
    REQUESTED_OPERATION,
    build_bounded_structural_bootstrap_state,
    build_fixture_bootstrap_invocation,
    build_slice36_acceptance_record,
    build_slice36_rollback_metadata,
    build_uninstalled_approved_caller_invocation,
    run_bounded_structural_bootstrap,
)
from .schema import (
    PRE_SLICE36_COMMIT,
    PRE_SLICE36_TREE,
    SLICE36_ACCEPTED_CHAIN,
    SLICE36_ACCEPTED_SCOPE,
    SLICE36_DEFERRED_SCOPE,
    SLICE36_INCREMENT_LABELS,
    SLICE36_MATHEMATICAL_DIRECTION,
    SLICE36_PERMANENT_BOUNDARIES,
    SLICE36G_ACCEPTED_HEAD,
    SLICE36G_ACCEPTED_TREE,
    SLICE36H_COMMIT_SUBJECT,
    SLICE36H_SCHEMA_VERSION,
    SLICE36H_SPEC_ID,
    SLICE36H_SPEC_VERSION,
    BootstrapIntegrationStatus,
    BootstrapInvocationKind,
    BootstrapStage,
    BootstrapStageReceipt,
    BootstrapStageStatus,
    BoundedStructuralBootstrapInvocation,
    BoundedStructuralBootstrapResult,
    BoundedStructuralBootstrapState,
    BoundedStructuralFixtureRecord,
    Slice36AcceptanceRecord,
    Slice36RollbackMetadata,
)
from .validation import (
    validate_bootstrap_adapter_for_slice36h,
    validate_bootstrap_stage_receipt,
    validate_bounded_structural_bootstrap_invocation,
    validate_bounded_structural_bootstrap_result,
    validate_bounded_structural_bootstrap_state,
    validate_bounded_structural_fixture,
    validate_slice36_acceptance_record,
    validate_slice36_rollback_metadata,
)

__all__ = (
    "PRE_SLICE36_COMMIT",
    "PRE_SLICE36_TREE",
    "SLICE36_ACCEPTED_CHAIN",
    "SLICE36_ACCEPTED_SCOPE",
    "SLICE36_DEFERRED_SCOPE",
    "SLICE36_INCREMENT_LABELS",
    "SLICE36_MATHEMATICAL_DIRECTION",
    "SLICE36_PERMANENT_BOUNDARIES",
    "SLICE36G_ACCEPTED_HEAD",
    "SLICE36G_ACCEPTED_TREE",
    "SLICE36H_COMMIT_SUBJECT",
    "SLICE36H_SCHEMA_VERSION",
    "SLICE36H_SPEC_ID",
    "SLICE36H_SPEC_VERSION",
    "BootstrapIntegrationStatus",
    "BootstrapInvocationKind",
    "BootstrapStage",
    "BootstrapStageReceipt",
    "BootstrapStageStatus",
    "BoundedStructuralBootstrapInvocation",
    "BoundedStructuralBootstrapResult",
    "BoundedStructuralBootstrapState",
    "BoundedStructuralFixtureRecord",
    "FIXTURE_GOVERNING",
    "FIXTURE_INCOMPLETE_QUOTATION",
    "FIXTURE_QUOTATION_CONFLICT",
    "FIXTURE_ZERO_DERIVATION",
    "REASON_COMPLETED_CANDIDATES",
    "REASON_COMPLETED_NON_PROGRESS",
    "REASON_DISABLED",
    "REQUESTED_OPERATION",
    "Slice36AcceptanceRecord",
    "Slice36RollbackMetadata",
    "build_bounded_structural_bootstrap_state",
    "build_fixture_bootstrap_invocation",
    "build_slice36_acceptance_record",
    "build_slice36_rollback_metadata",
    "build_uninstalled_approved_caller_invocation",
    "get_bounded_structural_fixture",
    "is_exact_accepted_bounded_structural_fixture",
    "list_bounded_structural_fixtures",
    "run_bounded_structural_bootstrap",
    "validate_bootstrap_adapter_for_slice36h",
    "validate_bootstrap_stage_receipt",
    "validate_bounded_structural_bootstrap_invocation",
    "validate_bounded_structural_bootstrap_result",
    "validate_bounded_structural_bootstrap_state",
    "validate_bounded_structural_fixture",
    "validate_slice36_acceptance_record",
    "validate_slice36_rollback_metadata",
)
