"""
forge/rmc_engine_v1/mea/__init__.py

Manifest Evolution Algebra (MEA) — Forge Discovery Kernel foundation.
Patch 275 adds the first read-only MEA runtime package inside Forge.

Layer boundary:
- RMC compiles meaning for the current utterance or step.
- MEA evolves unresolved problem manifests over multiple cycles.
- This package does not write memory, call an LLM, execute shell commands, or
  alter existing RMC runtime behavior.
"""

from .manifest_schema import (
    MEA_SCHEMA_VERSION,
    MEA_PATCH_ID,
    ProblemManifest,
    CandidateManifest,
    ClaimStatus,
    OutputPermission,
    PhaseState,
    DriftState,
    OperatorTrace,
    MemoryRef,
    Assumption,
    ValidationResult,
    build_manifest,
    build_144hz_test_manifest,
    canonical_hash,
    canonical_dict,
    validate_manifest,
    to_dict,
    from_dict,
    foundation_boundary,
)
from .unknown_detector import (
    detect_unknowns,
    UnknownVector,
    UnknownGap,
    GapType,
)

from .proof_debt_scorer import (
    PROOF_DEBT_SCORER_PATCH_ID,
    PROOF_DEBT_FORMULA,
    PROOF_DEBT_SCHEMA_VERSION,
    ProofDebtBand,
    EvidenceSupportProfile,
    ProofDebtScore,
    build_evidence_support_profile,
    score_proof_debt,
    scoring_boundary as proof_debt_scoring_boundary,
)
from .information_gain_scorer import (
    INFORMATION_GAIN_SCORER_PATCH_ID,
    INFORMATION_GAIN_FORMULA,
    INFORMATION_GAIN_SCHEMA_VERSION,
    InformationGainDelta,
    InformationGainScore,
    score_information_gain,
    scoring_boundary as information_gain_scoring_boundary,
)

from .convergence_scorer import (
    CONVERGENCE_SCORER_PATCH_ID,
    CONVERGENCE_FORMULA,
    CONVERGENCE_SCHEMA_VERSION,
    SuccessConditionScore,
    ConvergenceScore,
    score_convergence,
    scoring_boundary as convergence_scoring_boundary,
)
from .goal_ancestry_scorer import (
    GOAL_ANCESTRY_SCORER_PATCH_ID,
    GOAL_ANCESTRY_FORMULA,
    GOAL_ANCESTRY_SCHEMA_VERSION,
    GoalAncestryStepScore,
    GoalAncestryScore,
    score_goal_ancestry,
    scoring_boundary as goal_ancestry_scoring_boundary,
)
from .operator_cost_scorer import (
    OPERATOR_COST_SCORER_PATCH_ID,
    OPERATOR_COST_FORMULA,
    OPERATOR_COST_SCHEMA_VERSION,
    DEFAULT_OPERATOR_COST_SCHEDULE,
    OperatorCostEntry,
    OperatorCostScore,
    score_operator_cost,
    scoring_boundary as operator_cost_scoring_boundary,
)


from .operator_registry import (
    OPERATOR_REGISTRY_PATCH_ID,
    OPERATOR_REGISTRY_SCHEMA_VERSION,
    REPLAY_LAW_FORMULA,
    ParameterSpec,
    OperatorDefinition,
    ParameterValidationResult,
    OperatorRegistry,
    build_default_operator_registry,
    get_operator_definition,
    list_operator_definitions,
    validate_operator_parameters,
    apply_registered_operator,
    operator_registry_summary,
    operator_registry_boundary,
    canonical_parameter_hash,
)
from .replay_engine import (
    REPLAY_ENGINE_PATCH_ID,
    REPLAY_ENGINE_SCHEMA_VERSION,
    ReplayResult,
    ReplayStepReport,
    ReplayPathResult,
    replay_candidate,
    replay_operator_path,
    replay_engine_boundary,
    canonical_theta_hash,
)


from .claim_status_classifier import (
    CLAIM_STATUS_CLASSIFIER_PATCH_ID,
    CLAIM_STATUS_CLASSIFIER_SCHEMA_VERSION,
    CLAIM_STATUS_CLASSIFIER_FORMULA,
    DEFAULT_DRIFT_THRESHOLD,
    ClaimStatusClassification,
    ClaimStatusThresholds,
    classify_claim_status,
    classify_replay_result,
    claim_status_taxonomy,
    classifier_boundary as claim_status_classifier_boundary,
)

from .api_preview import (
    API_PREVIEW_PATCH_ID,
    API_PREVIEW_SCHEMA_VERSION,
    API_PREVIEW_MODE,
    MEA_READ_ONLY_PREVIEW_ROUTES,
    api_preview_boundary,
    operator_console_visibility_manifest,
    build_problem_manifest_preview,
    build_unknown_vector_preview,
    build_claim_status_preview,
    build_replay_preview,
    build_preview_payload,
)


from .seed_manifest_gate import (
    SEED_GATE_PATCH_ID,
    SEED_GATE_SCHEMA_VERSION,
    SEED_GATE_MODE,
    SEED_GATE_APPROVAL_TOKEN,
    SEED_GATE_POST_ROUTE,
    SEED_GATE_STATUS_ROUTE,
    SEED_GATE_ALIAS_ROUTE,
    SeedGateResult,
    seed_manifest_gate_boundary,
    seed_manifest_gate_status,
    evaluate_seed_manifest_request,
    build_seed_manifest_gate_preview,
    build_seed_manifest_gate_rejection_preview,
    clone_manifest_for_test,
)

from .discovery_kernel import (
    KERNEL_NAME,
    KERNEL_STAGE,
    KERNEL_PATCH_ID,
    ForgeDiscoveryKernelFoundation,
    build_foundation_kernel,
    kernel_identity,
    kernel_foundation_probe,
)

# Patch 279R compatibility export.
# main.py imports classifier_boundary from package root; Patch 279 exported only
# claim_status_classifier_boundary. Keep both names bound to the same read-only
# boundary function so endpoint imports and direct module imports stay coherent.
classifier_boundary = claim_status_classifier_boundary

MEA_VERSION = MEA_SCHEMA_VERSION
MEA_PATCH = "Patch 283R — MEA Hard Gate Report POST Dispatch Hotfix"
MEA_LAYER = "foundation"
MEA_FORGE_BASE = "Patch 274R rebased from uploaded current-state packet"

__all__ = [
    "MEA_VERSION",
    "MEA_PATCH",
    "MEA_LAYER",
    "MEA_FORGE_BASE",
    "MEA_SCHEMA_VERSION",
    "MEA_PATCH_ID",
    "ProblemManifest",
    "CandidateManifest",
    "ClaimStatus",
    "OutputPermission",
    "PhaseState",
    "DriftState",
    "OperatorTrace",
    "MemoryRef",
    "Assumption",
    "ValidationResult",
    "build_manifest",
    "build_144hz_test_manifest",
    "canonical_hash",
    "canonical_dict",
    "validate_manifest",
    "to_dict",
    "from_dict",
    "foundation_boundary",
    "detect_unknowns",
    "UnknownVector",
    "UnknownGap",
    "GapType",
    "PROOF_DEBT_SCORER_PATCH_ID",
    "PROOF_DEBT_FORMULA",
    "PROOF_DEBT_SCHEMA_VERSION",
    "ProofDebtBand",
    "EvidenceSupportProfile",
    "ProofDebtScore",
    "build_evidence_support_profile",
    "score_proof_debt",
    "proof_debt_scoring_boundary",
    "INFORMATION_GAIN_SCORER_PATCH_ID",
    "INFORMATION_GAIN_FORMULA",
    "INFORMATION_GAIN_SCHEMA_VERSION",
    "InformationGainDelta",
    "InformationGainScore",
    "score_information_gain",
    "information_gain_scoring_boundary",
    "CONVERGENCE_SCORER_PATCH_ID",
    "CONVERGENCE_FORMULA",
    "CONVERGENCE_SCHEMA_VERSION",
    "SuccessConditionScore",
    "ConvergenceScore",
    "score_convergence",
    "convergence_scoring_boundary",
    "GOAL_ANCESTRY_SCORER_PATCH_ID",
    "GOAL_ANCESTRY_FORMULA",
    "GOAL_ANCESTRY_SCHEMA_VERSION",
    "GoalAncestryStepScore",
    "GoalAncestryScore",
    "score_goal_ancestry",
    "goal_ancestry_scoring_boundary",
    "OPERATOR_COST_SCORER_PATCH_ID",
    "OPERATOR_COST_FORMULA",
    "OPERATOR_COST_SCHEMA_VERSION",
    "DEFAULT_OPERATOR_COST_SCHEDULE",
    "OperatorCostEntry",
    "OperatorCostScore",
    "score_operator_cost",
    "operator_cost_scoring_boundary",
    "OPERATOR_REGISTRY_PATCH_ID",
    "OPERATOR_REGISTRY_SCHEMA_VERSION",
    "REPLAY_LAW_FORMULA",
    "ParameterSpec",
    "OperatorDefinition",
    "ParameterValidationResult",
    "OperatorRegistry",
    "build_default_operator_registry",
    "get_operator_definition",
    "list_operator_definitions",
    "validate_operator_parameters",
    "apply_registered_operator",
    "operator_registry_summary",
    "operator_registry_boundary",
    "canonical_parameter_hash",
    "CLAIM_STATUS_CLASSIFIER_PATCH_ID",
    "CLAIM_STATUS_CLASSIFIER_SCHEMA_VERSION",
    "CLAIM_STATUS_CLASSIFIER_FORMULA",
    "DEFAULT_DRIFT_THRESHOLD",
    "ClaimStatusClassification",
    "ClaimStatusThresholds",
    "classify_claim_status",
    "classify_replay_result",
    "claim_status_taxonomy",
    "claim_status_classifier_boundary",
    "classifier_boundary",
    "API_PREVIEW_PATCH_ID",
    "API_PREVIEW_SCHEMA_VERSION",
    "API_PREVIEW_MODE",
    "MEA_READ_ONLY_PREVIEW_ROUTES",
    "api_preview_boundary",
    "operator_console_visibility_manifest",
    "build_problem_manifest_preview",
    "build_unknown_vector_preview",
    "build_claim_status_preview",
    "build_replay_preview",
    "build_preview_payload",
    "SEED_GATE_PATCH_ID",
    "SEED_GATE_SCHEMA_VERSION",
    "SEED_GATE_MODE",
    "SEED_GATE_APPROVAL_TOKEN",
    "SEED_GATE_POST_ROUTE",
    "SEED_GATE_STATUS_ROUTE",
    "SEED_GATE_ALIAS_ROUTE",
    "SeedGateResult",
    "seed_manifest_gate_boundary",
    "seed_manifest_gate_status",
    "evaluate_seed_manifest_request",
    "build_seed_manifest_gate_preview",
    "build_seed_manifest_gate_rejection_preview",
    "clone_manifest_for_test",
    "REPLAY_ENGINE_PATCH_ID",
    "REPLAY_ENGINE_SCHEMA_VERSION",
    "ReplayResult",
    "ReplayStepReport",
    "ReplayPathResult",
    "replay_candidate",
    "replay_operator_path",
    "replay_engine_boundary",
    "canonical_theta_hash",
    "CANDIDATE_SET_GATE_PATCH_ID",
    "CANDIDATE_SET_GATE_SCHEMA_VERSION",
    "CANDIDATE_SET_GATE_MODE",
    "CANDIDATE_SET_GATE_APPROVAL_TOKEN",
    "CANDIDATE_SET_GATE_STATUS_ROUTE",
    "CANDIDATE_SET_GATE_POST_ROUTE",
    "CANDIDATE_SET_GATE_ALIAS_ROUTE",
    "CANDIDATE_SET_PREVIEW_ROUTE",
    "CANDIDATE_PREVIEW_SCORE_FORMULA",
    "CandidatePreview",
    "candidate_set_gate_boundary",
    "candidate_set_gate_status",
    "build_candidate_set_preview",
    "evaluate_candidate_set_request",
    "build_candidate_set_gate_preview",
    "build_candidate_set_gate_rejection_preview",
    "HARD_GATE_REPORT_PATCH_ID",
    "HARD_GATE_REPORT_SCHEMA_VERSION",
    "HARD_GATE_REPORT_MODE",
    "HARD_GATE_REPORT_APPROVAL_TOKEN",
    "HARD_GATE_REPORT_STATUS_ROUTE",
    "HARD_GATE_REPORT_PREVIEW_ROUTE",
    "HARD_GATE_REPORT_POST_ROUTE",
    "HARD_GATE_REPORT_ALIAS_ROUTE",
    "HARD_GATE_FORMULA",
    "HardGateCheck",
    "CandidateHardGateReport",
    "hard_gate_report_boundary",
    "hard_gate_report_status",
    "evaluate_candidate_hard_gates",
    "build_hard_gate_report",
    "evaluate_hard_gate_report_request",
    "build_hard_gate_report_preview",
    "build_hard_gate_report_gate_preview",
    "build_hard_gate_report_rejection_preview",
    "KERNEL_NAME",
    "KERNEL_STAGE",
    "KERNEL_PATCH_ID",
    "ForgeDiscoveryKernelFoundation",
    "build_foundation_kernel",
    "kernel_identity",
    "kernel_foundation_probe",
]


from .candidate_set_gate import (
    CANDIDATE_SET_GATE_PATCH_ID,
    CANDIDATE_SET_GATE_SCHEMA_VERSION,
    CANDIDATE_SET_GATE_MODE,
    CANDIDATE_SET_GATE_APPROVAL_TOKEN,
    CANDIDATE_SET_GATE_STATUS_ROUTE,
    CANDIDATE_SET_GATE_POST_ROUTE,
    CANDIDATE_SET_GATE_ALIAS_ROUTE,
    CANDIDATE_SET_PREVIEW_ROUTE,
    CANDIDATE_PREVIEW_SCORE_FORMULA,
    CandidatePreview,
    candidate_set_gate_boundary,
    candidate_set_gate_status,
    build_candidate_set_preview,
    evaluate_candidate_set_request,
    build_candidate_set_gate_preview,
    build_candidate_set_gate_rejection_preview,
)


from .hard_gate_report import (
    HARD_GATE_REPORT_PATCH_ID,
    HARD_GATE_REPORT_SCHEMA_VERSION,
    HARD_GATE_REPORT_MODE,
    HARD_GATE_REPORT_APPROVAL_TOKEN,
    HARD_GATE_REPORT_STATUS_ROUTE,
    HARD_GATE_REPORT_PREVIEW_ROUTE,
    HARD_GATE_REPORT_POST_ROUTE,
    HARD_GATE_REPORT_ALIAS_ROUTE,
    HARD_GATE_FORMULA,
    HardGateCheck,
    CandidateHardGateReport,
    hard_gate_report_boundary,
    hard_gate_report_status,
    evaluate_candidate_hard_gates,
    build_hard_gate_report,
    evaluate_hard_gate_report_request,
    build_hard_gate_report_preview,
    build_hard_gate_report_gate_preview,
    build_hard_gate_report_rejection_preview,
)
