"""Slice 42B deterministic validation, identity, version, and lifecycle exports."""

from .canonical import (
    CANONICAL_FIELD_ORDERS,
    CANONICAL_FIELD_ORDER_VERSION,
    SUPPORTED_RECORD_TYPES,
    OutwardExpressionCanonicalizationError,
    canonical_field_order,
    canonical_json_bytes,
    canonical_record_bytes,
    canonical_record_mapping,
    canonicalize_field_pairs,
    deterministic_digest,
    deterministic_record_digest,
    stable_identifier,
)
from .identity import (
    expected_authority_requirement_id,
    expected_bundle_digest,
    expected_bundle_id,
    expected_expression_eligibility_status_id,
    expected_expression_plan_boundary_id,
    expected_expression_receipt_boundary_id,
    expected_expression_trace_boundary_id,
    expected_governed_outward_meaning_boundary_id,
    expected_lifecycle_record_id,
    expected_lifecycle_transition_id,
    expected_obligation_custody_id,
    expected_realized_expression_boundary_id,
    expected_record_id,
    expected_runtime_schema_record_id,
    expected_source_custody_id,
    expected_version_custody_id,
    identity_field,
    identity_namespace,
    with_expected_bundle_identity,
    with_expected_id,
)
from .lifecycle import assert_lifecycle_transition, evaluate_lifecycle_transition
from .rules import (
    OUTWARD_EXPRESSION_LIFECYCLE_TRANSITION_RULES,
    OutwardExpressionLifecycleTransitionRule,
    lifecycle_transition_allowed,
    lifecycle_transition_rule,
)
from .schema import (
    DIGEST_ALGORITHM,
    SLICE42B_ACCEPTED_PARENT_HEAD,
    SLICE42B_ACCEPTED_PARENT_SUBJECT,
    SLICE42B_ACCEPTED_PARENT_TREE,
    SLICE42B_SCHEMA_VERSION,
    SUPPORTED_RUNTIME_SCHEMA_VERSIONS,
    SUPPORTED_RUNTIME_SPEC_VERSIONS,
    SUPPORTED_VALIDATION_PROFILE_VERSIONS,
    VALIDATION_PROFILE_VERSION,
    OutwardExpressionGovernanceBundle,
    OutwardExpressionLifecycleDecision,
    OutwardExpressionLifecycleRecord,
    OutwardExpressionLifecycleStage,
    OutwardExpressionLifecycleTransitionKind,
    OutwardExpressionLifecycleTransitionRecord,
    OutwardExpressionValidationCode,
    OutwardExpressionValidationError,
    OutwardExpressionValidationIssue,
    OutwardExpressionValidationReport,
    OutwardExpressionVersionCustody,
)
from .validation import (
    CORE_RECORD_TYPES,
    assert_valid_governance_bundle,
    assert_valid_runtime_schema_record,
    assert_valid_version_custody,
    expected_predecessor_references,
    expected_record_schema_versions,
    validate_authority_requirement,
    validate_expression_eligibility_status,
    validate_expression_plan_boundary,
    validate_expression_receipt_boundary,
    validate_expression_trace_boundary,
    validate_field_pairs,
    validate_governance_bundle,
    validate_governed_outward_meaning_boundary,
    validate_identity_collection,
    validate_lifecycle_record,
    validate_lifecycle_transition_record,
    validate_preservation_obligation_custody,
    validate_realized_expression_boundary,
    validate_runtime_schema_record,
    validate_source_custody,
    validate_version_custody,
)

__all__ = tuple(name for name in globals() if not name.startswith("_"))
