"""Public API for Slice 42D preservation-obligation projection."""

from .authority import (
    DIGEST_ALGORITHM,
    SLICE42D_ACCEPTED_PARENT_HEAD,
    SLICE42D_ACCEPTED_PARENT_SUBJECT,
    SLICE42D_ACCEPTED_PARENT_TREE,
    SLICE42D_BOUNDED_CERTAINTY_REF,
    SLICE42D_DELIVERY_NOT_AUTHORIZED_REF,
    SLICE42D_EVIDENCE_NOT_VALIDATED_REF,
    SLICE42D_EXTERNAL_RESOURCE_NOT_LOADED_REF,
    SLICE42D_GOVERNING_AUTHORITY_REFS,
    SLICE42D_MEMORY_NO_WRITE_AUTHORITY_REF,
    SLICE42D_OBLIGATION_CATEGORY_NAMES,
    SLICE42D_PERMANENT_BOUNDARIES,
    SLICE42D_PRIVACY_IDENTITY_BOUNDARY_REF,
    SLICE42D_PROFILE_KEY,
    SLICE42D_PROFILE_VERSION,
    SLICE42D_PROHIBITED_AUTHORITY,
    SLICE42D_PROJECTION_AUTHORITY_KEY,
    SLICE42D_SCHEMA_VERSION,
    SLICE42D_SPEC_ID,
    SLICE42D_SPEC_VERSION,
)
from .canonical import (
    PreservationObligationCanonicalizationError,
    canonical_json_bytes,
    deterministic_digest,
    stable_identifier,
)
from .identity import (
    expected_package_digest,
    expected_package_id,
    expected_record_id,
    expected_result_digest,
    expected_result_id,
    with_expected_id,
    with_expected_package_identity,
    with_expected_result_identity,
)
from .projector import (
    derive_obligation_values,
    project_preservation_obligations,
)
from .schema import (
    ExpressionObligationPackage,
    PreservationObligationProjectionAuthorityRecord,
    PreservationObligationProjectionFinding,
    PreservationObligationProjectionFindingKind,
    PreservationObligationProjectionInput,
    PreservationObligationProjectionResult,
    PreservationObligationProjectionValidationCode,
    PreservationObligationProjectionValidationError,
    PreservationObligationProjectionValidationIssue,
    PreservationObligationProjectionValidationReport,
)
from .validation import (
    assert_valid_projection_input,
    assert_valid_projection_result,
    validate_obligation_package,
    validate_projection_authority_record,
    validate_projection_input,
    validate_projection_result,
)


__all__ = (
    "DIGEST_ALGORITHM",
    "ExpressionObligationPackage",
    "PreservationObligationCanonicalizationError",
    "PreservationObligationProjectionAuthorityRecord",
    "PreservationObligationProjectionFinding",
    "PreservationObligationProjectionFindingKind",
    "PreservationObligationProjectionInput",
    "PreservationObligationProjectionResult",
    "PreservationObligationProjectionValidationCode",
    "PreservationObligationProjectionValidationError",
    "PreservationObligationProjectionValidationIssue",
    "PreservationObligationProjectionValidationReport",
    "SLICE42D_ACCEPTED_PARENT_HEAD",
    "SLICE42D_ACCEPTED_PARENT_SUBJECT",
    "SLICE42D_ACCEPTED_PARENT_TREE",
    "SLICE42D_BOUNDED_CERTAINTY_REF",
    "SLICE42D_DELIVERY_NOT_AUTHORIZED_REF",
    "SLICE42D_EVIDENCE_NOT_VALIDATED_REF",
    "SLICE42D_EXTERNAL_RESOURCE_NOT_LOADED_REF",
    "SLICE42D_GOVERNING_AUTHORITY_REFS",
    "SLICE42D_MEMORY_NO_WRITE_AUTHORITY_REF",
    "SLICE42D_OBLIGATION_CATEGORY_NAMES",
    "SLICE42D_PERMANENT_BOUNDARIES",
    "SLICE42D_PRIVACY_IDENTITY_BOUNDARY_REF",
    "SLICE42D_PROFILE_KEY",
    "SLICE42D_PROFILE_VERSION",
    "SLICE42D_PROHIBITED_AUTHORITY",
    "SLICE42D_PROJECTION_AUTHORITY_KEY",
    "SLICE42D_SCHEMA_VERSION",
    "SLICE42D_SPEC_ID",
    "SLICE42D_SPEC_VERSION",
    "assert_valid_projection_input",
    "assert_valid_projection_result",
    "canonical_json_bytes",
    "derive_obligation_values",
    "deterministic_digest",
    "expected_package_digest",
    "expected_package_id",
    "expected_record_id",
    "expected_result_digest",
    "expected_result_id",
    "project_preservation_obligations",
    "stable_identifier",
    "validate_obligation_package",
    "validate_projection_authority_record",
    "validate_projection_input",
    "validate_projection_result",
    "with_expected_id",
    "with_expected_package_identity",
    "with_expected_result_identity",
)
